# Generated by Django 4.2.25 on 2025-10-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='rbac.role', verbose_name='Роли'),
        ),
    ]
